#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# generate Sphinx HTML documentation, including API docs

rm -f docs/pygogo.rst
rm -f docs/modules.rst
sphinx-apidoc -o docs/ pygogo
cd docs
make clean
make html
open _build/html/index.html
