sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - pypy3.7-7.3.2

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - PYTHONHASHSEED=94967295

matrix:
  fast_finish: true
  allow_failures:
  - python: pypy3.7-7.3.2

notifications:
  email:
    on_success: always

branches:
  except:
    - /^v[0-9]/

before_install:
  - pip install -U pip

install:
  - pip install -r dev-requirements.txt

script:
  - manage lint && manage test

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then exit 0; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then exit 0; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.9" ]]; then exit 0; fi
